-- Better Auth's rate limit counter, generated by `@better-auth/cli generate`
-- once `rateLimit.storage` moved to the database.
--
-- Only the new table is here: 0001 already created the other four, and a
-- migration that re-ran them would fail on the second apply.

create table "rateLimit" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);
